### ISSUE TITLE
Vraagje: zou je deze ook nog op andere manieren kunnen oplossen?

### ISSUE THREAD

**Issue by remimestdagh** [DanteDeRuwe/mongodb-exercises#1]
https://github.com/DanteDeRuwe/mongodb-exercises/blob/48f4a27bb638bd0cd4c949438d5aa0fe4dba5330/2.%20aggregate/bel20.js#L53

**Comment by dantederuwe-hogent** [comment]
Heb je zelf een voorstel? ;)

**Comment by DanteDeRuwe** [comment]
Heb je zelf een voorstel in gedachten?
